# Cleaning Data in Pandas DataFrames

## 1. Import libraries and dependencies

In [20]:
# Import the pandas and pathlib libraries

## 2. Create a Path to the File Using Pathlib

In [21]:
# Use the Pathlib libary to set the path to the CSV

## 3. Read the CSV into a Pandas DataFrame

In [22]:
# Use the file path to read the CSV into a DataFrame and display a few rows

,Unnamed: 0,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,0,1.0,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,1,2.0,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,2,3.0,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,3,4.0,NaN,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,4,5.0,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47

## 4. View Column Data Types

In [23]:
# Use the `dtypes` attribute to list the column data types

Unnamed: 0      int64
Person_ID     float64
Last_Name      object
First_Name     object
Gender         object
University     object
Occupation     object
Salary        float64
Email          object
Age             int64
dtype: object

## 5. Drop Extraneous Columns

In [24]:
# Use the `drop` function to drop specific columns

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,1.0,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,2.0,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,3.0,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,4.0,NaN,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,5.0,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47

---

## 6. Identify Data Quality Issues

### 1. Identify the Number of Rows

In [6]:
# Use the `count` function to view count of non-null values for each column

Person_ID      996
Last_Name      990
First_Name     993
Gender         998
University     991
Occupation     998
Salary         998
Email          992
Age           1000
dtype: int64

### 2. Identify Frequency Counts of the `first_name` Column

In [7]:
# Identifying frequency counts of the `first_name` column

Ailbert       3
Israel        3
Christie      2
Joey          2
Dore          2
Garv          2
Alano         2
Fanny         2
Cher          2
Cooper        2
Antonio       2
Jolene        2
Kennan        2
Elaina        2
Linn          2
Lea           2
Julian        2
Anastassia    2
Ado           2
Kalindi       2
Marty         2
Rollins       2
Lacie         2
Ruy           2
Darcy         2
Gal           2
Sasha         2
Mable         2
Darsie        2
Merline       2
             ..
Shauna        1
Leicester     1
Amalita       1
Nial          1
Gwendolen     1
Malena        1
Danice        1
Rodney        1
Isadora       1
Hamish        1
Ezri          1
Miguelita     1
Caleb         1
Wells         1
Kelcey        1
Powell        1
Willi         1
Dud           1
Onida         1
Abra          1
Burr          1
Myrtice       1
Kalil         1
Kati          1
Allsun        1
Lucas         1
Huntley       1
Diarmid       1
Monique       1
Beatrice      1
Name: First_Name, Length: 914, dtype: int64

### 3. Identify Null Values

In [8]:
# Checking for null

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
970,False,False,False,False,False,False,False,False,False
971,False,False,False,False,False,False,False,False,False
972,False,False,False,False,False,False,False,False,False
973,False,False,False,False,False,False,False,False,False
974,False,False,False,False,False,False,False,False,False
975,False,False,False,False,False,False,False,False,False
976,False,False,False,False,False,False,False,False,False
977,False,False,False,False,False,False,False,False,False
978,False,False,False,False,False,False,False,False,False
979,False,False,False,False,False,False,False,False,False
980,False,False,False,False,False,False,False,False,False
981,False,False,False,False,False,False,False,False,False
982,False,False,False,False,False,False,False,False,False
983,False,False,False,False,False,False,False,False,False
984,False,False,False,False,False,False,False,False,False
985,False,False,False,False,False,False,False,False,False
986,False,False,False,False,False,False,False,False,False
987,False,False,False,False,False,False,False,False,False
988,False,False,False,False,False,False,False,False,False
989,False,True,False,False,False,False,False,False,False
990,False,False,False,False,False,False,False,False,False
991,False,False,False,False,False,False,False,False,False
992,False,False,False,False,False,False,False,False,False
993,False,False,False,False,False,False,False,False,False
994,False,False,False,False,False,False,False,False,False
995,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False

### 4. Determine the Number of Nulls

In [9]:
# Determining number of nulls

Person_ID      4
Last_Name     10
First_Name     7
Gender         2
University     9
Occupation     2
Salary         2
Email          8
Age            0
dtype: int64

### 5. Determining the Percentage of Nulls for each Column

In [10]:
# Determining percentage of nulls

Person_ID     0.4
Last_Name     1.0
First_Name    0.7
Gender        0.2
University    0.9
Occupation    0.2
Salary        0.2
Email         0.8
Age           0.0
dtype: float64

### 6. Check for Duplicate Rows

In [19]:
# Use the `duplicated` function to determine the existance of duplicate rows: True or False

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999     True
Length: 973, dtype: bool

### 7. Check for Duplicate `first_name` and `last_name Values

In [15]:
# Use the `duplicated` function in conjunction with a list of columns to 
# determine the existence of duplicate rows based on the selected columns

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999     True
Length: 973, dtype: bool

---

## 7. Resolve Data Quality Issues

### 1. Fill First_Name and Last_Name Null Values with Default Value "Unnamed"

In [11]:
# Cleanse nulls from DataFrame by filling na

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,1.0,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,2.0,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,3.0,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,4.0,Unnamed,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,5.0,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47
5,6.0,Snozzwell,Antonio,Male,Babcock University,Technical Writer,119916.0,asnozzwell5@mysql.com,49
6,7.0,Neathway,Darya,Female,Molloy College,Administrative Officer,77705.0,dneathway6@seesaa.net,64
7,8.0,Duding,Helaina,Female,St. Paul University,Staff Scientist,57166.0,hduding7@topsy.com,26
8,9.0,Franzolini,Gerhardine,Female,Fundação Educacional de Ituverava,Environmental Specialist,73051.0,gfranzolini8@msn.com,22
9,10.0,Traut,Charo,Female,Cornell University,Programmer III,90631.0,ctraut9@oracle.com,45
10,11.0,Crepin,Horst,Male,College of William and Mary,Cost Accountant,68077.0,hcrepina@google.it,49
11,12.0,Symcox,Eleanora,Female,Universidad Capitain General Gerardo Barrios,Help Desk Technician,70765.0,esymcoxb@rambler.ru,57
12,13.0,Sandwich,Ian,Male,Fukuoka Dental College,Environmental Specialist,77657.0,isandwichc@cdc.gov,55
13,14.0,Luggar,Padraic,Male,ENIC Telecom Lille 1,Chief Design Engineer,93013.0,pluggard@sina.com.cn,62
14,15.0,Raynor,Allard,Male,Islamic University of Gaza,Senior Cost Accountant,86283.0,araynore@pbs.org,29
15,16.0,Skechley,Broderic,Male,Universität Hannover,Sales Associate,82699.0,bskechleyf@t-online.de,33
16,17.0,Lehrmann,Gabriela,Female,Aichi Prefectural University,Health Coach III,69729.0,glehrmanng@house.gov,35
17,18.0,Klimpt,Aigneis,Female,Institute of Textile Technology,Tax Accountant,71815.0,aklimpth@pinterest.com,34
18,19.0,Hymus,Logan,Male,Universidad Nacional Experimental Romulo Gallegos,Account Coordinator,86337.0,lhymusi@nature.com,57
19,20.0,Dossett,Nial,Male,Technische Universität München,Recruiter,98904.0,ndossettj@bandcamp.com,55
20,21.0,Meikle,Geneva,Female,Dar al Hekma College,Quality Control Specialist,116539.0,gmeiklek@hubpages.com,35
21,22.0,Crowth,Elianora,Female,Victoria International University,Help Desk Operator,78951.0,ecrowthl@virginia.edu,23
22,23.0,Petcher,Flem,Male,Syktyvkar State University,Web Developer III,80941.0,fpetcherm@netvibes.com,55
23,24.0,Gillbee,Emory,Male,Sojourner-Douglass College,Librarian,54590.0,egillbeen@china.com.cn,43
24,25.0,Gutowska,Cirillo,Male,Mansfield University of Pennsylvania,Staff Scientist,104212.0,cgutowskao@elpais.com,38
25,26.0,Pinel,Henrietta,Female,Georg-Simon-Ohm-Fachhochschule Nürnberg,Business Systems Development Analyst,115360.0,hpinelp@aol.com,24
26,27.0,Dunnet,Virgil,Male,Liaquat University of Medical & Health Science...,Marketing Assistant,75639.0,vdunnetq@lycos.com,26
27,28.0,Bigham,Nadeen,Female,London Institute of Management and Technology,Teacher,79569.0,nbighamr@gmpg.org,55
28,29.0,Haydney,Dorene,Female,Southern New Hampshire University,Research Assistant IV,112098.0,dhaydneys@blogger.com,55
29,30.0,Lages,Adah,Female,Kunmimg University of Science and Technology,VP Accounting,64177.0,alagest@nytimes.com,31
...,...,...,...,...,...,...,...,...,...
970,971.0,Perchard,Ennis,Male,University of Exeter,Accounting Assistant I,109716.0,eperchardqy@storify.com,64
971,972.0,Attfield,Sigrid,Female,Universidad de La Salle,Senior Quality Engineer,93769.0,sattfieldqz@nationalgeographic.com,42
972,973.0,Spurdle,Kathi,Female,United States Sports Academy,VP Marketing,56669.0,kspurdler0@ucla.edu,48
973,974.0,Haspineall,Antonio,Male,Lansbridge University,Legal Assistant,71608.0,ahaspineallr1@simplemachines.org,33
974,975.0,Shoveller,Bernadina,Female,Midwestern State University,Assistant Manager,63355.0,bshovellerr2@ca.gov,33
975,976.0,Pickett,Nanete,Female,Ecole Nationale Supérieure de Physique de Gren...,Human Resources Manager,108835.0,npickettr3@businesswire.com,61
976,977.0,Lethbrig,Hastie,Male,Ecole Polytechnique,Electrical Engineer,73842.0,hlethbrigr4@europa.eu,32
977,978.0,McPhillimey,Danice,Female,Université d'Artois,Automation Specialist II,71578.0,dmcphillimeyr5@flickr.com,60
978,979.0,Yurchenko,Kale,Male,Southeast Missouri State University,Biostatistician IV,54576.0,kyurchenkor6@netscape.com,54
979,980.0,Eykel,Dillon,Male,Shorter College,Pharmacist,110623.0,deykelr7@independent.co.uk,58
980,981.0,Tarbox,Alley,Male,University of Alaska (System),Speech Pathologist,91118.0,atarboxr8@comcast.net,28
981,982.0,Cocksedge,Nydia,Female,University of Wroclaw,Quality Engineer,63085.0,ncocksedger9@goo.gl,38
982,983.0,Boutellier,Dayna,Female,Ummah University,Software Engineer I,70141.0,dboutellierra@tumblr.com,22
983,984.0,Maharey,Angie,Female,Utsunomiya University,Accountant I,65560.0,amahareyrb@w3.org,61
984,985.0,Strongitharm,Felice,Male,University of Engineering and Technology Peshawar,Actuary,60366.0,fstrongitharmrc@pen.io,43
985,986.0,Grint,Humbert,Male,National Technical University (Kharkiv Polytec...,Financial Analyst,114068.0,hgrintrd@google.com.br,64
986,987.0,Morratt,Kaye,Female,Shaheed Zulifkar Ali Bhutto Institute of Scien...,Senior Sales Associate,82362.0,kmorrattre@youku.com,53
987,988.0,Karolczyk,Jillie,Female,Providence College,Dental Hygienist,52966.0,jkarolczykrf@unblog.fr,26
988,989.0,Waker,Estrellita,Female,New England College,Database Administrator I,80118.0,ewakerrg@angelfire.com,59
989,990.0,Unnamed,Urson,Male,Wilberforce University,Librarian,79603.0,uenrdigorh@gmpg.org,48
990,991.0,Hampshire,Julian,Male,Johnson & Wales University,Chemical Engineer,79024.0,jhampshireri@disqus.com,26
991,992.0,Glossop,Davine,Female,Université René Descartes (Paris V),VP Quality Control,50599.0,dglossoprj@goodreads.com,47
992,993.0,Rugg,Dorothea,Female,Universidad Politécnica de El Salvador,VP Marketing,114586.0,druggrk@miitbeian.gov.cn,51
993,994.0,Griffitts,Damaris,Female,The College of Wooster,Senior Editor,113339.0,dgriffittsrl@mapquest.com,42
994,995.0,Jeacop,Iggy,Male,University of Greenwich,Sales Associate,82726.0,ijeacoprm@4shared.com,22
995,996.0,Crumpton,Meta,Female,ECAM - Institut Supérieur Industriel,Registered Nurse,57060.0,mcrumptonrn@qq.com,52
996,997.0,Gilford,Gunar,Male,Smolny University,Marketing Manager,76109.0,ggilfordro@yandex.ru,32
997,998.0,Gurling,Lucretia,Female,Institut Teknologi Telkom,Software Engineer III,92115.0,lgurlingrp@de.vu,48
998,999.0,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53
999,999.0,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53

### 2. Drop Remaining Records with Nulls from DataFrame

In [12]:
# Use the `dropna` function to drop whole records that have at least one null value

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,1.0,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,2.0,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,3.0,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,4.0,Unnamed,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,5.0,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47
5,6.0,Snozzwell,Antonio,Male,Babcock University,Technical Writer,119916.0,asnozzwell5@mysql.com,49
6,7.0,Neathway,Darya,Female,Molloy College,Administrative Officer,77705.0,dneathway6@seesaa.net,64
7,8.0,Duding,Helaina,Female,St. Paul University,Staff Scientist,57166.0,hduding7@topsy.com,26
8,9.0,Franzolini,Gerhardine,Female,Fundação Educacional de Ituverava,Environmental Specialist,73051.0,gfranzolini8@msn.com,22
9,10.0,Traut,Charo,Female,Cornell University,Programmer III,90631.0,ctraut9@oracle.com,45
10,11.0,Crepin,Horst,Male,College of William and Mary,Cost Accountant,68077.0,hcrepina@google.it,49
11,12.0,Symcox,Eleanora,Female,Universidad Capitain General Gerardo Barrios,Help Desk Technician,70765.0,esymcoxb@rambler.ru,57
12,13.0,Sandwich,Ian,Male,Fukuoka Dental College,Environmental Specialist,77657.0,isandwichc@cdc.gov,55
13,14.0,Luggar,Padraic,Male,ENIC Telecom Lille 1,Chief Design Engineer,93013.0,pluggard@sina.com.cn,62
14,15.0,Raynor,Allard,Male,Islamic University of Gaza,Senior Cost Accountant,86283.0,araynore@pbs.org,29
15,16.0,Skechley,Broderic,Male,Universität Hannover,Sales Associate,82699.0,bskechleyf@t-online.de,33
16,17.0,Lehrmann,Gabriela,Female,Aichi Prefectural University,Health Coach III,69729.0,glehrmanng@house.gov,35
17,18.0,Klimpt,Aigneis,Female,Institute of Textile Technology,Tax Accountant,71815.0,aklimpth@pinterest.com,34
18,19.0,Hymus,Logan,Male,Universidad Nacional Experimental Romulo Gallegos,Account Coordinator,86337.0,lhymusi@nature.com,57
19,20.0,Dossett,Nial,Male,Technische Universität München,Recruiter,98904.0,ndossettj@bandcamp.com,55
20,21.0,Meikle,Geneva,Female,Dar al Hekma College,Quality Control Specialist,116539.0,gmeiklek@hubpages.com,35
21,22.0,Crowth,Elianora,Female,Victoria International University,Help Desk Operator,78951.0,ecrowthl@virginia.edu,23
22,23.0,Petcher,Flem,Male,Syktyvkar State University,Web Developer III,80941.0,fpetcherm@netvibes.com,55
23,24.0,Gillbee,Emory,Male,Sojourner-Douglass College,Librarian,54590.0,egillbeen@china.com.cn,43
24,25.0,Gutowska,Cirillo,Male,Mansfield University of Pennsylvania,Staff Scientist,104212.0,cgutowskao@elpais.com,38
25,26.0,Pinel,Henrietta,Female,Georg-Simon-Ohm-Fachhochschule Nürnberg,Business Systems Development Analyst,115360.0,hpinelp@aol.com,24
26,27.0,Dunnet,Virgil,Male,Liaquat University of Medical & Health Science...,Marketing Assistant,75639.0,vdunnetq@lycos.com,26
27,28.0,Bigham,Nadeen,Female,London Institute of Management and Technology,Teacher,79569.0,nbighamr@gmpg.org,55
28,29.0,Haydney,Dorene,Female,Southern New Hampshire University,Research Assistant IV,112098.0,dhaydneys@blogger.com,55
29,30.0,Lages,Adah,Female,Kunmimg University of Science and Technology,VP Accounting,64177.0,alagest@nytimes.com,31
...,...,...,...,...,...,...,...,...,...
970,971.0,Perchard,Ennis,Male,University of Exeter,Accounting Assistant I,109716.0,eperchardqy@storify.com,64
971,972.0,Attfield,Sigrid,Female,Universidad de La Salle,Senior Quality Engineer,93769.0,sattfieldqz@nationalgeographic.com,42
972,973.0,Spurdle,Kathi,Female,United States Sports Academy,VP Marketing,56669.0,kspurdler0@ucla.edu,48
973,974.0,Haspineall,Antonio,Male,Lansbridge University,Legal Assistant,71608.0,ahaspineallr1@simplemachines.org,33
974,975.0,Shoveller,Bernadina,Female,Midwestern State University,Assistant Manager,63355.0,bshovellerr2@ca.gov,33
975,976.0,Pickett,Nanete,Female,Ecole Nationale Supérieure de Physique de Gren...,Human Resources Manager,108835.0,npickettr3@businesswire.com,61
976,977.0,Lethbrig,Hastie,Male,Ecole Polytechnique,Electrical Engineer,73842.0,hlethbrigr4@europa.eu,32
977,978.0,McPhillimey,Danice,Female,Université d'Artois,Automation Specialist II,71578.0,dmcphillimeyr5@flickr.com,60
978,979.0,Yurchenko,Kale,Male,Southeast Missouri State University,Biostatistician IV,54576.0,kyurchenkor6@netscape.com,54
979,980.0,Eykel,Dillon,Male,Shorter College,Pharmacist,110623.0,deykelr7@independent.co.uk,58
980,981.0,Tarbox,Alley,Male,University of Alaska (System),Speech Pathologist,91118.0,atarboxr8@comcast.net,28
981,982.0,Cocksedge,Nydia,Female,University of Wroclaw,Quality Engineer,63085.0,ncocksedger9@goo.gl,38
982,983.0,Boutellier,Dayna,Female,Ummah University,Software Engineer I,70141.0,dboutellierra@tumblr.com,22
983,984.0,Maharey,Angie,Female,Utsunomiya University,Accountant I,65560.0,amahareyrb@w3.org,61
984,985.0,Strongitharm,Felice,Male,University of Engineering and Technology Peshawar,Actuary,60366.0,fstrongitharmrc@pen.io,43
985,986.0,Grint,Humbert,Male,National Technical University (Kharkiv Polytec...,Financial Analyst,114068.0,hgrintrd@google.com.br,64
986,987.0,Morratt,Kaye,Female,Shaheed Zulifkar Ali Bhutto Institute of Scien...,Senior Sales Associate,82362.0,kmorrattre@youku.com,53
987,988.0,Karolczyk,Jillie,Female,Providence College,Dental Hygienist,52966.0,jkarolczykrf@unblog.fr,26
988,989.0,Waker,Estrellita,Female,New England College,Database Administrator I,80118.0,ewakerrg@angelfire.com,59
989,990.0,Unnamed,Urson,Male,Wilberforce University,Librarian,79603.0,uenrdigorh@gmpg.org,48
990,991.0,Hampshire,Julian,Male,Johnson & Wales University,Chemical Engineer,79024.0,jhampshireri@disqus.com,26
991,992.0,Glossop,Davine,Female,Université René Descartes (Paris V),VP Quality Control,50599.0,dglossoprj@goodreads.com,47
992,993.0,Rugg,Dorothea,Female,Universidad Politécnica de El Salvador,VP Marketing,114586.0,druggrk@miitbeian.gov.cn,51
993,994.0,Griffitts,Damaris,Female,The College of Wooster,Senior Editor,113339.0,dgriffittsrl@mapquest.com,42
994,995.0,Jeacop,Iggy,Male,University of Greenwich,Sales Associate,82726.0,ijeacoprm@4shared.com,22
995,996.0,Crumpton,Meta,Female,ECAM - Institut Supérieur Industriel,Registered Nurse,57060.0,mcrumptonrn@qq.com,52
996,997.0,Gilford,Gunar,Male,Smolny University,Marketing Manager,76109.0,ggilfordro@yandex.ru,32
997,998.0,Gurling,Lucretia,Female,Institut Teknologi Telkom,Software Engineer III,92115.0,lgurlingrp@de.vu,48
998,999.0,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53
999,999.0,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53

### 3. Check Null Counts for Each Column (Again)

In [13]:
# Use the `isnull` function in conjunction with the `sum` function to count the number of null values for each column

Person_ID     0
Last_Name     0
First_Name    0
Gender        0
University    0
Occupation    0
Salary        0
Email         0
Age           0
dtype: int64

### 4. Cleanse data by Dropping Duplicates

In [16]:
# Use the `drop_duplicates` function with the `subset` parameter to 
# drop duplicates based on a selection of columns

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,1.0,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,2.0,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,3.0,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,4.0,Unnamed,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,5.0,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47
5,6.0,Snozzwell,Antonio,Male,Babcock University,Technical Writer,119916.0,asnozzwell5@mysql.com,49
6,7.0,Neathway,Darya,Female,Molloy College,Administrative Officer,77705.0,dneathway6@seesaa.net,64
7,8.0,Duding,Helaina,Female,St. Paul University,Staff Scientist,57166.0,hduding7@topsy.com,26
8,9.0,Franzolini,Gerhardine,Female,Fundação Educacional de Ituverava,Environmental Specialist,73051.0,gfranzolini8@msn.com,22
9,10.0,Traut,Charo,Female,Cornell University,Programmer III,90631.0,ctraut9@oracle.com,45
10,11.0,Crepin,Horst,Male,College of William and Mary,Cost Accountant,68077.0,hcrepina@google.it,49
11,12.0,Symcox,Eleanora,Female,Universidad Capitain General Gerardo Barrios,Help Desk Technician,70765.0,esymcoxb@rambler.ru,57
12,13.0,Sandwich,Ian,Male,Fukuoka Dental College,Environmental Specialist,77657.0,isandwichc@cdc.gov,55
13,14.0,Luggar,Padraic,Male,ENIC Telecom Lille 1,Chief Design Engineer,93013.0,pluggard@sina.com.cn,62
14,15.0,Raynor,Allard,Male,Islamic University of Gaza,Senior Cost Accountant,86283.0,araynore@pbs.org,29
15,16.0,Skechley,Broderic,Male,Universität Hannover,Sales Associate,82699.0,bskechleyf@t-online.de,33
16,17.0,Lehrmann,Gabriela,Female,Aichi Prefectural University,Health Coach III,69729.0,glehrmanng@house.gov,35
17,18.0,Klimpt,Aigneis,Female,Institute of Textile Technology,Tax Accountant,71815.0,aklimpth@pinterest.com,34
18,19.0,Hymus,Logan,Male,Universidad Nacional Experimental Romulo Gallegos,Account Coordinator,86337.0,lhymusi@nature.com,57
19,20.0,Dossett,Nial,Male,Technische Universität München,Recruiter,98904.0,ndossettj@bandcamp.com,55
20,21.0,Meikle,Geneva,Female,Dar al Hekma College,Quality Control Specialist,116539.0,gmeiklek@hubpages.com,35
21,22.0,Crowth,Elianora,Female,Victoria International University,Help Desk Operator,78951.0,ecrowthl@virginia.edu,23
22,23.0,Petcher,Flem,Male,Syktyvkar State University,Web Developer III,80941.0,fpetcherm@netvibes.com,55
23,24.0,Gillbee,Emory,Male,Sojourner-Douglass College,Librarian,54590.0,egillbeen@china.com.cn,43
24,25.0,Gutowska,Cirillo,Male,Mansfield University of Pennsylvania,Staff Scientist,104212.0,cgutowskao@elpais.com,38
25,26.0,Pinel,Henrietta,Female,Georg-Simon-Ohm-Fachhochschule Nürnberg,Business Systems Development Analyst,115360.0,hpinelp@aol.com,24
26,27.0,Dunnet,Virgil,Male,Liaquat University of Medical & Health Science...,Marketing Assistant,75639.0,vdunnetq@lycos.com,26
27,28.0,Bigham,Nadeen,Female,London Institute of Management and Technology,Teacher,79569.0,nbighamr@gmpg.org,55
28,29.0,Haydney,Dorene,Female,Southern New Hampshire University,Research Assistant IV,112098.0,dhaydneys@blogger.com,55
29,30.0,Lages,Adah,Female,Kunmimg University of Science and Technology,VP Accounting,64177.0,alagest@nytimes.com,31
...,...,...,...,...,...,...,...,...,...
969,970.0,Barby,Lionello,Male,Universidad de Monterrey,VP Product Management,99301.0,lbarbyqx@disqus.com,58
970,971.0,Perchard,Ennis,Male,University of Exeter,Accounting Assistant I,109716.0,eperchardqy@storify.com,64
971,972.0,Attfield,Sigrid,Female,Universidad de La Salle,Senior Quality Engineer,93769.0,sattfieldqz@nationalgeographic.com,42
972,973.0,Spurdle,Kathi,Female,United States Sports Academy,VP Marketing,56669.0,kspurdler0@ucla.edu,48
973,974.0,Haspineall,Antonio,Male,Lansbridge University,Legal Assistant,71608.0,ahaspineallr1@simplemachines.org,33
974,975.0,Shoveller,Bernadina,Female,Midwestern State University,Assistant Manager,63355.0,bshovellerr2@ca.gov,33
975,976.0,Pickett,Nanete,Female,Ecole Nationale Supérieure de Physique de Gren...,Human Resources Manager,108835.0,npickettr3@businesswire.com,61
976,977.0,Lethbrig,Hastie,Male,Ecole Polytechnique,Electrical Engineer,73842.0,hlethbrigr4@europa.eu,32
977,978.0,McPhillimey,Danice,Female,Université d'Artois,Automation Specialist II,71578.0,dmcphillimeyr5@flickr.com,60
978,979.0,Yurchenko,Kale,Male,Southeast Missouri State University,Biostatistician IV,54576.0,kyurchenkor6@netscape.com,54
979,980.0,Eykel,Dillon,Male,Shorter College,Pharmacist,110623.0,deykelr7@independent.co.uk,58
980,981.0,Tarbox,Alley,Male,University of Alaska (System),Speech Pathologist,91118.0,atarboxr8@comcast.net,28
981,982.0,Cocksedge,Nydia,Female,University of Wroclaw,Quality Engineer,63085.0,ncocksedger9@goo.gl,38
982,983.0,Boutellier,Dayna,Female,Ummah University,Software Engineer I,70141.0,dboutellierra@tumblr.com,22
983,984.0,Maharey,Angie,Female,Utsunomiya University,Accountant I,65560.0,amahareyrb@w3.org,61
984,985.0,Strongitharm,Felice,Male,University of Engineering and Technology Peshawar,Actuary,60366.0,fstrongitharmrc@pen.io,43
985,986.0,Grint,Humbert,Male,National Technical University (Kharkiv Polytec...,Financial Analyst,114068.0,hgrintrd@google.com.br,64
986,987.0,Morratt,Kaye,Female,Shaheed Zulifkar Ali Bhutto Institute of Scien...,Senior Sales Associate,82362.0,kmorrattre@youku.com,53
987,988.0,Karolczyk,Jillie,Female,Providence College,Dental Hygienist,52966.0,jkarolczykrf@unblog.fr,26
988,989.0,Waker,Estrellita,Female,New England College,Database Administrator I,80118.0,ewakerrg@angelfire.com,59
989,990.0,Unnamed,Urson,Male,Wilberforce University,Librarian,79603.0,uenrdigorh@gmpg.org,48
990,991.0,Hampshire,Julian,Male,Johnson & Wales University,Chemical Engineer,79024.0,jhampshireri@disqus.com,26
991,992.0,Glossop,Davine,Female,Université René Descartes (Paris V),VP Quality Control,50599.0,dglossoprj@goodreads.com,47
992,993.0,Rugg,Dorothea,Female,Universidad Politécnica de El Salvador,VP Marketing,114586.0,druggrk@miitbeian.gov.cn,51
993,994.0,Griffitts,Damaris,Female,The College of Wooster,Senior Editor,113339.0,dgriffittsrl@mapquest.com,42
994,995.0,Jeacop,Iggy,Male,University of Greenwich,Sales Associate,82726.0,ijeacoprm@4shared.com,22
995,996.0,Crumpton,Meta,Female,ECAM - Institut Supérieur Industriel,Registered Nurse,57060.0,mcrumptonrn@qq.com,52
996,997.0,Gilford,Gunar,Male,Smolny University,Marketing Manager,76109.0,ggilfordro@yandex.ru,32
997,998.0,Gurling,Lucretia,Female,Institut Teknologi Telkom,Software Engineer III,92115.0,lgurlingrp@de.vu,48
998,999.0,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53

### 5. Convert Columns to Different DataTypes

In [17]:
# Use the `as_type` function to convert `Person_ID` from `float` to `int`

,Person_ID,Last_Name,First_Name,Gender,University,Occupation,Salary,Email,Age
0,1,Lenormand,Keriann,Female,Aurora University,Nurse Practicioner,58135.0,klenormand0@businessinsider.com,27
1,2,Rupke,Huntley,Male,Osaka University of Economics,Project Manager,96053.0,hrupke1@reuters.com,22
2,3,Dalgarnowch,Gorden,Male,Ludong University,Environmental Tech,59196.0,gdalgarnowch2@microsoft.com,40
3,4,Unnamed,Cullie,Male,Université des Sciences et de la Technologie d...,Legal Assistant,88493.0,cputten3@nymag.com,62
4,5,Strangman,Ariel,Female,Boise State University,Project Manager,89073.0,astrangman4@bravesites.com,47
5,6,Snozzwell,Antonio,Male,Babcock University,Technical Writer,119916.0,asnozzwell5@mysql.com,49
6,7,Neathway,Darya,Female,Molloy College,Administrative Officer,77705.0,dneathway6@seesaa.net,64
7,8,Duding,Helaina,Female,St. Paul University,Staff Scientist,57166.0,hduding7@topsy.com,26
8,9,Franzolini,Gerhardine,Female,Fundação Educacional de Ituverava,Environmental Specialist,73051.0,gfranzolini8@msn.com,22
9,10,Traut,Charo,Female,Cornell University,Programmer III,90631.0,ctraut9@oracle.com,45
10,11,Crepin,Horst,Male,College of William and Mary,Cost Accountant,68077.0,hcrepina@google.it,49
11,12,Symcox,Eleanora,Female,Universidad Capitain General Gerardo Barrios,Help Desk Technician,70765.0,esymcoxb@rambler.ru,57
12,13,Sandwich,Ian,Male,Fukuoka Dental College,Environmental Specialist,77657.0,isandwichc@cdc.gov,55
13,14,Luggar,Padraic,Male,ENIC Telecom Lille 1,Chief Design Engineer,93013.0,pluggard@sina.com.cn,62
14,15,Raynor,Allard,Male,Islamic University of Gaza,Senior Cost Accountant,86283.0,araynore@pbs.org,29
15,16,Skechley,Broderic,Male,Universität Hannover,Sales Associate,82699.0,bskechleyf@t-online.de,33
16,17,Lehrmann,Gabriela,Female,Aichi Prefectural University,Health Coach III,69729.0,glehrmanng@house.gov,35
17,18,Klimpt,Aigneis,Female,Institute of Textile Technology,Tax Accountant,71815.0,aklimpth@pinterest.com,34
18,19,Hymus,Logan,Male,Universidad Nacional Experimental Romulo Gallegos,Account Coordinator,86337.0,lhymusi@nature.com,57
19,20,Dossett,Nial,Male,Technische Universität München,Recruiter,98904.0,ndossettj@bandcamp.com,55
20,21,Meikle,Geneva,Female,Dar al Hekma College,Quality Control Specialist,116539.0,gmeiklek@hubpages.com,35
21,22,Crowth,Elianora,Female,Victoria International University,Help Desk Operator,78951.0,ecrowthl@virginia.edu,23
22,23,Petcher,Flem,Male,Syktyvkar State University,Web Developer III,80941.0,fpetcherm@netvibes.com,55
23,24,Gillbee,Emory,Male,Sojourner-Douglass College,Librarian,54590.0,egillbeen@china.com.cn,43
24,25,Gutowska,Cirillo,Male,Mansfield University of Pennsylvania,Staff Scientist,104212.0,cgutowskao@elpais.com,38
25,26,Pinel,Henrietta,Female,Georg-Simon-Ohm-Fachhochschule Nürnberg,Business Systems Development Analyst,115360.0,hpinelp@aol.com,24
26,27,Dunnet,Virgil,Male,Liaquat University of Medical & Health Science...,Marketing Assistant,75639.0,vdunnetq@lycos.com,26
27,28,Bigham,Nadeen,Female,London Institute of Management and Technology,Teacher,79569.0,nbighamr@gmpg.org,55
28,29,Haydney,Dorene,Female,Southern New Hampshire University,Research Assistant IV,112098.0,dhaydneys@blogger.com,55
29,30,Lages,Adah,Female,Kunmimg University of Science and Technology,VP Accounting,64177.0,alagest@nytimes.com,31
...,...,...,...,...,...,...,...,...,...
970,971,Perchard,Ennis,Male,University of Exeter,Accounting Assistant I,109716.0,eperchardqy@storify.com,64
971,972,Attfield,Sigrid,Female,Universidad de La Salle,Senior Quality Engineer,93769.0,sattfieldqz@nationalgeographic.com,42
972,973,Spurdle,Kathi,Female,United States Sports Academy,VP Marketing,56669.0,kspurdler0@ucla.edu,48
973,974,Haspineall,Antonio,Male,Lansbridge University,Legal Assistant,71608.0,ahaspineallr1@simplemachines.org,33
974,975,Shoveller,Bernadina,Female,Midwestern State University,Assistant Manager,63355.0,bshovellerr2@ca.gov,33
975,976,Pickett,Nanete,Female,Ecole Nationale Supérieure de Physique de Gren...,Human Resources Manager,108835.0,npickettr3@businesswire.com,61
976,977,Lethbrig,Hastie,Male,Ecole Polytechnique,Electrical Engineer,73842.0,hlethbrigr4@europa.eu,32
977,978,McPhillimey,Danice,Female,Université d'Artois,Automation Specialist II,71578.0,dmcphillimeyr5@flickr.com,60
978,979,Yurchenko,Kale,Male,Southeast Missouri State University,Biostatistician IV,54576.0,kyurchenkor6@netscape.com,54
979,980,Eykel,Dillon,Male,Shorter College,Pharmacist,110623.0,deykelr7@independent.co.uk,58
980,981,Tarbox,Alley,Male,University of Alaska (System),Speech Pathologist,91118.0,atarboxr8@comcast.net,28
981,982,Cocksedge,Nydia,Female,University of Wroclaw,Quality Engineer,63085.0,ncocksedger9@goo.gl,38
982,983,Boutellier,Dayna,Female,Ummah University,Software Engineer I,70141.0,dboutellierra@tumblr.com,22
983,984,Maharey,Angie,Female,Utsunomiya University,Accountant I,65560.0,amahareyrb@w3.org,61
984,985,Strongitharm,Felice,Male,University of Engineering and Technology Peshawar,Actuary,60366.0,fstrongitharmrc@pen.io,43
985,986,Grint,Humbert,Male,National Technical University (Kharkiv Polytec...,Financial Analyst,114068.0,hgrintrd@google.com.br,64
986,987,Morratt,Kaye,Female,Shaheed Zulifkar Ali Bhutto Institute of Scien...,Senior Sales Associate,82362.0,kmorrattre@youku.com,53
987,988,Karolczyk,Jillie,Female,Providence College,Dental Hygienist,52966.0,jkarolczykrf@unblog.fr,26
988,989,Waker,Estrellita,Female,New England College,Database Administrator I,80118.0,ewakerrg@angelfire.com,59
989,990,Unnamed,Urson,Male,Wilberforce University,Librarian,79603.0,uenrdigorh@gmpg.org,48
990,991,Hampshire,Julian,Male,Johnson & Wales University,Chemical Engineer,79024.0,jhampshireri@disqus.com,26
991,992,Glossop,Davine,Female,Université René Descartes (Paris V),VP Quality Control,50599.0,dglossoprj@goodreads.com,47
992,993,Rugg,Dorothea,Female,Universidad Politécnica de El Salvador,VP Marketing,114586.0,druggrk@miitbeian.gov.cn,51
993,994,Griffitts,Damaris,Female,The College of Wooster,Senior Editor,113339.0,dgriffittsrl@mapquest.com,42
994,995,Jeacop,Iggy,Male,University of Greenwich,Sales Associate,82726.0,ijeacoprm@4shared.com,22
995,996,Crumpton,Meta,Female,ECAM - Institut Supérieur Industriel,Registered Nurse,57060.0,mcrumptonrn@qq.com,52
996,997,Gilford,Gunar,Male,Smolny University,Marketing Manager,76109.0,ggilfordro@yandex.ru,32
997,998,Gurling,Lucretia,Female,Institut Teknologi Telkom,Software Engineer III,92115.0,lgurlingrp@de.vu,48
998,999,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53
999,999,Yang,Andrew,Male,Rutgers University School of Business,Curriculum Engineer,60000.0,ayang@codedrills.com,53

## 8. Save Cleansed Data to New CSV

In [18]:
# Save modified DataFrame to the Resources folder. Use the `index` parameter set to `False` to exclude saving the index.